### ISSUE TITLE
how to add an entry to your awesome list? 

### ISSUE THREAD

**Issue by alexlib** [protontypes/awesome-sustainable-technology#2]
Please consider the @meironz work on the multiscale Ulva model - it is a central part of the sustinability concept of off-shore macroalgae (Ulva, etc.) growth and biorefinery, as well as sutiable for the waste water and afluent absorptions.

https://github.com/alexliberzonlab/Multiscale_Ulva

**Comment by Ly0n** [comment]
Thanks @alexlib. It fits well into Bioenergy and especially here we have too few projects  I also checked for other projects in the same domain but could not anything.  The documentation looks good and the project has definitely an impact to preserve energy supply and life resources.  I can't find anything comparable either, which makes the project additionally "awesome".

We did the silent launch of the list yesterday and it is still not ready. I hope we can share it tomorrow publicly. 
 The contribution guide is under construction and it would be nice to get more such contributions from you in the future.
