### ISSUE TITLE
Creative Commons

### ISSUE THREAD

**Issue by PythonLinks** [protontypes/awesome-sustainable-technology#5]
Do you also accept Creative Commons JSON Data?

**Comment by RichardLitt** [comment]
I'm not sure how that's relevant to Awesome Sustainable Tech. Could you clarify?

**Comment by PythonLinks** [comment]
Right.
I should have been more specific. 
Do you also accept Creative Commons Data related to sustainable technology?

I am thinking of doing a map of either sustainable agricuural farms, permaculture, or regenrative agriculture. 
Much like Maps.Howie2020.tech. 

And also I am thinking of releasing the Green Party Map data as creative commons data.

**Comment by RichardLitt** [comment]
Good questions. I'm not the maintainer, so I'll let Tobias answer for this!

**Comment by Ly0n** [comment]
> I am thinking of doing a map of either sustainable agricuural farms, permaculture, or regenrative agriculture.
Much like Maps.Howie2020.tech.

@PythonLinks I must honestly tell you that I have absolutely no idea about sustainable agriculture. That is why there is nothing listed here. But I think this is an important part of it. You are very welcome to make a pull-request about the project. It could be interesting to see the growth of sustainable agriculture from a scientific or technological point of view.

You will also find more information in our contribution guide:
https://github.com/protontypes/awesome-sustainable-technology/blob/master/CONTRIBUTING.md

Do you know of any other projects that might fit in well here? To open a new category we should have at least 3 projects. What are good keywords that can help you to search?


> And also I am thinking of releasing the Green Party Map data as creative commons data.

The focus of this list is more on the technology part than the political part. When such a party is releasing technology open source they are very welcome on the list.

**Comment by tjarkdoering** [comment]
From the [Open Source Hardware Association](https://www.oshwa.org/2014/05/21/cc-oshw/):

Not all CC licenses are compatible with open source values.
But the following are:
1) Creative Commons Attribution: CC BY
2) Creative Commons Attribution-ShareAlike: CC BY-SA
3) Creative Commons Public Domain Dedication: CC0

I would suggest allowing the three mentioned CC licenses as "a open source license" (as taken from CONTRIBUTING.md).
They are also introduced as open on [choosealicense.com](https://choosealicense.com/non-software/).

@PythonLinks I would therefore add to the answer above by saying: Depends upon the CC license used.

**Comment by Ly0n** [comment]
Hey @PythonLinks. We do have an Agriculture section now:
https://github.com/protontypes/awesome-sustainable-technology/tree/agri#agriculture-and-nutrition
You are very welcomed to add you projects here. The branch will be merged next week.
